name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alexander.christudhasan@teliacompany.com/docker-image-autobuild:latest
    - name: Push the Docker image
      run: Jfrog login -u alexander.christudhasan@teliacompany.com -p ${{ secrets.PASSWORD }} && docker push alexander.christudhasan@teliacompany.com/docker-image-autobuild:latest
